export const NECTOR_MODE = "_n_mode";
export const NECTOR_AUTHORIZATION = "_n_auth_token";
export const NECTOR_SHARED_SECRET = "_n_shared_secret";

export const API_BASE_HEADER = {
	"accept": "application/json",
	"content-type": "application/json",
	"x-source": "web"
};

// dispatchers

export const INTERNAL_DISPATCH = "INTERNAL_DISPATCH";

export const API_OTP_DISPATCH = "API_OTP_DISPATCH";
export const API_FORGOT_PASSWORD_DISPATCH = "API_FORGOT_PASSWORD_DISPATCH";

export const API_OPEN_GET_SYSTEMINFOS = "API_OPEN_GET_SYSTEMINFOS";
export const API_MERCHANT_GET_ENTITY = "API_MERCHANT_GET_ENTITY";
export const API_MERCHANT_GET_KYC = "API_MERCHANT_GET_KYC";
export const API_MERCHANT_GET_SETTING = "API_MERCHANT_GET_SETTING";

export const API_MERCHANT_LIST_API_DISPATCH = "API_MERCHANT_LIST_API_DISPATCH";
export const API_MERCHANT_LIST_LEAD_DISPATCH = "API_MERCHANT_LIST_LEAD_DISPATCH";
export const API_MERCHANT_LIST_DEAL_DISPATCH = "API_MERCHANT_LIST_DEAL_DISPATCH";
export const API_MERCHANT_LIST_TASK_DISPATCH = "API_MERCHANT_LIST_TASK_DISPATCH";
export const API_MERCHANT_LIST_SWAP_DISPATCH = "API_MERCHANT_LIST_SWAP_DISPATCH";
export const API_MERCHANT_LIST_COUPON_DISPATCH = "API_MERCHANT_LIST_COUPON_DISPATCH";
export const API_MERCHANT_LIST_WALLET_DISPATCH = "API_MERCHANT_LIST_WALLET_DISPATCH";
export const API_MERCHANT_LIST_WALLETTRANSACTION_DISPATCH = "API_MERCHANT_LIST_WALLETTRANSACTION_DISPATCH";
export const API_MERCHANT_LIST_COUPONCODE_DISPATCH = "API_MERCHANT_LIST_COUPONCODE_DISPATCH";
export const API_MERCHANT_LIST_CURRENCY_DISPATCH = "API_MERCHANT_LIST_CURRENCY_DISPATCH";
export const API_MERCHANT_LIST_UPLOAD_DISPATCH = "API_MERCHANT_LIST_UPLOAD_DISPATCH";
export const API_MERCHANT_LIST_REVIEW_DISPATCH = "API_MERCHANT_LIST_REVIEW_DISPATCH";
export const API_MERCHANT_LIST_LOGINACTIVITY_DISPATCH = "API_MERCHANT_LIST_LOGINACTIVITY_DISPATCH";
export const API_MERCHANT_LIST_TASKACTIVITY_DISPATCH = "API_MERCHANT_LIST_TASKACTIVITY_DISPATCH";
export const API_MERCHANT_LIST_NOTIFICATION_DISPATCH = "API_MERCHANT_LIST_NOTIFICATION_DISPATCH";
export const API_MERCHANT_LIST_STAT_DISPATCH = "API_MERCHANT_LIST_STAT_DISPATCH";

export const API_LOGIN_DISPATCH = "API_LOGIN_DISPATCH";
export const API_LOGOUT_DISPATCH = "API_LOGOUT_DISPATCH";

export const API_SUCCESS_DISPATCH = "API_SUCCESS_DISPATCH";
export const API_IGNORE_DISPATCH = "API_IGNORE_DISPATCH";
export const API_ERROR_DISPATCH = "API_ERROR_DISPATCH";



