export const NODE_ENV = "NODE_ENV";

export const REACT_APP_SERVICE_PORT = "REACT_APP_SERVICE_PORT";
export const REACT_APP_SERVICE_HOST = "REACT_APP_SERVICE_HOST";
export const REACT_APP_SERVICE_NAME = "REACT_APP_SERVICE_NAME";

export const REACT_APP_API_BASE_PROD_URL = "REACT_APP_API_BASE_PROD_URL";
export const REACT_APP_API_BASE_DEV_URL = "REACT_APP_API_BASE_DEV_URL";

export const REACT_APP_HMAC_ALGO = "REACT_APP_HMAC_ALGO";